### ISSUE TITLE
Run the following command to report an error：python setup.py develop --no_cuda_ext

### ISSUE THREAD

**Issue by xlnn** [megvii-research/NAFNet#100]
Hello，Run the following command to report an error：python setup.py develop --no_cuda_ext：
![image](https://user-images.githubusercontent.com/57608826/229348423-c1d103ef-2af2-44cb-a3c4-ab46bcdf5ae2.png)

**> (pytorch2) root@notebook-under-model1-1yznilo-notebook-0:/workspace/algorithm/tt/NAFNet# python setup.py develop --no_cuda_ext
> /root/anaconda3/envs/pytorch2/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
>   warnings.warn(
> WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/cython/
> WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/cython/
> ERROR: Could not find a version that satisfies the requirement cython (from versions: none)
> ERROR: No matching distribution found for cython
> Traceback (most recent call last):
>   File "/root/anaconda3/envs/pytorch2/lib/python3.8/site-packages/setuptools/installer.py", line 82, in fetch_build_egg
>     subprocess.check_call(cmd)
>   File "/root/anaconda3/envs/pytorch2/lib/python3.8/subprocess.py", line 364, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['/root/anaconda3/envs/pytorch2/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpw5v8cis9', '--quiet', 'cython']' returned non-zero exit status 1.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "setup.py", line 157, in <module>
>     setup(
>   File "/root/anaconda3/envs/pytorch2/lib/python3.8/site-packages/setuptools/__init__.py", line 86, in setup
>     _install_setup_requires(attrs)
>   File "/root/anaconda3/envs/pytorch2/lib/python3.8/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
>     dist.fetch_build_eggs(dist.setup_requires)
>   File "/root/anaconda3/envs/pytorch2/lib/python3.8/site-packages/setuptools/dist.py", line 874, in fetch_build_eggs
>     resolved_dists = pkg_resources.working_set.resolve(
>   File "/root/anaconda3/envs/pytorch2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 789, in resolve
>     dist = best[req.key] = env.best_match(
>   File "/root/anaconda3/envs/pytorch2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1075, in best_match
>     return self.obtain(req, installer)
>   File "/root/anaconda3/envs/pytorch2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1087, in obtain
>     return installer(requirement)
>   File "/root/anaconda3/envs/pytorch2/lib/python3.8/site-packages/setuptools/dist.py", line 944, in fetch_build_egg
>     return fetch_build_egg(self, req)
>   File "/root/anaconda3/envs/pytorch2/lib/python3.8/site-packages/setuptools/installer.py", line 84, in fetch_build_egg
>     raise DistutilsError(str(e)) from e
> distutils.errors.DistutilsError: Command '['/root/anaconda3/envs/pytorch2/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpw5v8cis9', '--quiet', 'cython']' returned non-zero exit status 1.**

Thank you!

**Comment by XIXI1029** [comment]
解决了吗

**Comment by Wyz2927** [comment]
> 解决了吗

大佬解决了吗

**Comment by Wyz2927** [comment]
> > 解决了吗
> 
> 大佬解决了吗
破案了，最终原因是setuptools版本的问题。安装setuptools==78.1.1后就没问题了。可参考：https://blog.csdn.net/weixin_43912083/article/details/148203228
