### ISSUE TITLE
Not enough memory available to process your request

### ISSUE THREAD

**Issue by clasking2** [megvii-research/NAFNet#126]
Paste log:

Traceback (most recent call last):
File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/cog/server/worker.py", line 217, in _predict
result = predict(**payload)
File "predict.py", line 79, in predict
single_image_inference(model, inp, str(out_path))
File "predict.py", line 101, in single_image_inference
model.test()
File "/src/basicsr/models/image_restoration_model.py", line 247, in test
pred = self.net_g(self.lq[i:j])
File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
return forward_call(*input, **kwargs)
File "/src/basicsr/models/archs/NAFNet_arch.py", line 141, in forward
x = encoder(x)
File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
return forward_call(*input, **kwargs)
File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/torch/nn/modules/container.py", line 141, in forward
input = module(input)
File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
return forward_call(*input, **kwargs)
File "/src/basicsr/models/archs/NAFNet_arch.py", line 62, in forward
x = self.norm1(x)
File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
return forward_call(*input, **kwargs)
File "/src/basicsr/models/archs/arch_util.py", line 300, in forward
return LayerNormFunction.apply(x, self.weight, self.bias, self.eps)
File "/src/basicsr/models/archs/arch_util.py", line 271, in forward
var = (x - mu).pow(2).mean(1, keepdim=True)
RuntimeError: CUDA out of memory. Tried to allocate 4.27 GiB (GPU 0; 14.58 GiB total capacity; 10.46 GiB already allocated; 213.31 MiB free; 13.40 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by hayk-manukyan-dev** [comment]
Same problem. Is there any solution?

**Comment by ZhaoYeung** [comment]
> Same problem. Is there any solution?
I met the same question. I changed the batch size into smaller one, which is 4, soled the problem.

**Comment by hayk-manukyan-dev** [comment]
> > Same problem. Is there any solution?
> > I met the same question. I changed the batch size into smaller one, which is 4, soled the problem.

I trying to use test part and in .yml files there is not batch size option. Please can you help with that case

**Comment by ZhaoYeung** [comment]
> > > Same problem. Is there any solution?
> > > I met the same question. I changed the batch size into smaller one, which is 4, soled the problem.
> 
> I trying to use test part and in .yml files there is not batch size option. Please can you help with that case

![1701761162872](https://github.com/megvii-research/NAFNet/assets/63694568/509f34a6-229d-4a5d-b16f-257f4e356908)

**Comment by hayk-manukyan-dev** [comment]
> > > > Same problem. Is there any solution?
> > > > I met the same question. I changed the batch size into smaller one, which is 4, soled the problem.
> > 
> > 
> > I trying to use test part and in .yml files there is not batch size option. Please can you help with that case
> 
> ![1701761162872](https://private-user-images.githubusercontent.com/63694568/287957347-509f34a6-229d-4a5d-b16f-257f4e356908.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MTMzNzQsIm5iZiI6MTcwMTgxMzA3NCwicGF0aCI6Ii82MzY5NDU2OC8yODc5NTczNDctNTA5ZjM0YTYtMjI5ZC00YTVkLWIxNmYtMjU3ZjRlMzU2OTA4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDIxNTExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmMzRiNWIyOGY2ODM0NjlmOGRhYzA1ZDRjNTJkMjE5ZTBhMGRiZjRiZDI4NjAxYzNjZGIwNTc4ZGI5M2VjNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T6BzVsK1GkX01Oxd-3j1C6IHrbeXlLAjce9S8CzY668)


I thought train and test are not run each other and if change train it will have no action on test commands.
Now I get you, thank you very much 👍 👍 👍
