### ISSUE TITLE
train with single GPU

### ISSUE THREAD

**Issue by Heavenbest** [megvii-research/NAFNet#63]
2022-08-18 15:41:56,733 INFO: Dataset PairedImageDataset - gopro-test is created.
2022-08-18 15:41:56,733 INFO: Number of val images/folders in gopro-test: 1194
.. cosineannealingLR
2022-08-18 15:41:59,165 INFO: Model [ImageRestorationModel] is created.
2022-08-18 15:41:59,321 INFO: Start training from epoch: 0, iter: 0
2022-08-18 15:42:54,563 INFO: [NAFNe..][epoch:  0, iter:     200, lr:(9.998e-04,)] [eta: 1:30:56, time (data): 0.272 (0.003)] l_pix: -3.8901e+01
2022-08-18 15:43:49,139 INFO: [NAFNe..][epoch:  0, iter:     400, lr:(9.990e-04,)] [eta: 1:29:35, time (data): 0.272 (0.003)] l_pix: -4.1002e+01
2022-08-18 15:44:44,883 INFO: [NAFNe..][epoch:  0, iter:     600, lr:(9.978e-04,)] [eta: 1:29:08, time (data): 0.275 (0.003)] l_pix: -4.7450e+01
2022-08-18 15:45:41,114 INFO: [NAFNe..][epoch:  0, iter:     800, lr:(9.961e-04,)] [eta: 1:28:39, time (data): 0.275 (0.003)] l_pix: -5.7533e+01
2022-08-18 15:46:37,352 INFO: [NAFNe..][epoch:  1, iter:   1,000, lr:(9.939e-04,)] [eta: 1:27:59, time (data): 0.278 (0.005)] l_pix: -5.5011e+01
2022-08-18 15:35:10,613 WARNING: nondist_validation is not implemented. Run dist_validation.
Test train_image_0063_s072: 100%|████████████████████████████████████████████████████████| 1194/1194 [02:23<00:00,  8.32image/s]
Traceback (most recent call last):
  File "/data/pengshan/deblur_image/NAFNet-main/basicsr/train.py", line 305, in <module>
    main()
  File "/data/pengshan/deblur_image/NAFNet-main/basicsr/train.py", line 270, in main
    model.validation(val_loader, current_iter, tb_logger,
  File "/data/pengshan/deblur_image/NAFNet-main/basicsr/models/base_model.py", line 57, in validation
    return self.nondist_validation(dataloader, current_iter, tb_logger,
  File "/data/pengshan/deblur_image/NAFNet-main/basicsr/models/image_restoration_model.py", line 385, in nondist_validation
    self.dist_validation(*args, **kwargs)
  File "/data/pengshan/deblur_image/NAFNet-main/basicsr/models/image_restoration_model.py", line 365, in dist_validation
    torch.distributed.reduce(metrics, dst=0)
  File "/data/pengshan/miniconda3/envs/pytorch-blur/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1469, in reduce
    default_pg = _get_default_group()
  File "/data/pengshan/miniconda3/envs/pytorch-blur/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 429, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
 
使用单个GPU训练，使用的是我自己的数据集，出现上述错误，麻烦帮忙看下是哪里的问题。
这个能使用单卡训练吗？

**Comment by mayorx** [comment]
您好， 看上去是在validation的时候用到了分布式训练的一些参数导致的问题， 

单卡训练可以考虑使用
``` 
python -m torch.distributed.launch --nproc_per_node=1 --master_port=4321 basicsr/train.py -opt _PATH_TO_YOUR_CONFIG_ --launcher pytorch
```
避免特殊处理的麻烦

谢谢您对NAFNe的关注

**Comment by xywxy** [comment]
> 您好， 看上去是在validation的时候用到了分布式训练的一些参数导致的问题，
> 
> 单卡训练可以考虑使用
> 
> ```
> python -m torch.distributed.launch --nproc_per_node=1 --master_port=4321 basicsr/train.py -opt _PATH_TO_YOUR_CONFIG_ --launcher pytorch
> ```
> 
> 避免特殊处理的麻烦
> 
> 谢谢您对NAFNe的关注

你好，因为你们团队拥有更好及更多的GPU，我们普通学生实验室只有单卡的情况下如何调整呢？
在单卡训练是否需要对迭代次数iters及学习率lr进行调整，你们是8卡训练，请问我将iters*8，学习率除以8, batch size根据GPU显存增大，请问这样处理是否正确呢？

**Comment by dzw007** [comment]
请问单卡训练的问题解决了吗，我也出现了上述问题。但是作者提供的语句python -m torch.distributed.launch --nproc_per_node=1 --master_port=4321 basicsr/train.py -opt _PATH_TO_YOUR_CONFIG_ --launcher pytorch我不是很懂。

**Comment by wangwangzhang9527** [comment]
> 请问单卡训练的问题解决了吗，我也出现了上述问题。但是作者提供的语句python -m torch.distributed.launch --nproc_per_node=1 --master_port=4321 basicsr/train.py -opt _PATH_TO_YOUR_CONFIG_ --launcher pytorch我不是很懂。

PATH_TO_YOUR_CONFIG 就是你的配置文件 按照原来的就可以

**Comment by Albert6666666666** [comment]
> 2022-08-18 15:41:56,733 INFO: Dataset PairedImageDataset - gopro-test is created. 2022-08-18 15:41:56,733 INFO: Number of val images/folders in gopro-test: 1194 .. cosineannealingLR 2022-08-18 15:41:59,165 INFO: Model [ImageRestorationModel] is created. 2022-08-18 15:41:59,321 INFO: Start training from epoch: 0, iter: 0 2022-08-18 15:42:54,563 INFO: [NAFNe..][epoch: 0, iter: 200, lr:(9.998e-04,)] [eta: 1:30:56, time (data): 0.272 (0.003)] l_pix: -3.8901e+01 2022-08-18 15:43:49,139 INFO: [NAFNe..][epoch: 0, iter: 400, lr:(9.990e-04,)] [eta: 1:29:35, time (data): 0.272 (0.003)] l_pix: -4.1002e+01 2022-08-18 15:44:44,883 INFO: [NAFNe..][epoch: 0, iter: 600, lr:(9.978e-04,)] [eta: 1:29:08, time (data): 0.275 (0.003)] l_pix: -4.7450e+01 2022-08-18 15:45:41,114 INFO: [NAFNe..][epoch: 0, iter: 800, lr:(9.961e-04,)] [eta: 1:28:39, time (data): 0.275 (0.003)] l_pix: -5.7533e+01 2022-08-18 15:46:37,352 INFO: [NAFNe..][epoch: 1, iter: 1,000, lr:(9.939e-04,)] [eta: 1:27:59, time (data): 0.278 (0.005)] l_pix: -5.5011e+01 2022-08-18 15:35:10,613 WARNING: nondist_validation is not implemented. Run dist_validation. Test train_image_0063_s072: 100%|████████████████████████████████████████████████████████| 1194/1194 [02:23<00:00, 8.32image/s] Traceback (most recent call last): File "/data/pengshan/deblur_image/NAFNet-main/basicsr/train.py", line 305, in main() File "/data/pengshan/deblur_image/NAFNet-main/basicsr/train.py", line 270, in main model.validation(val_loader, current_iter, tb_logger, File "/data/pengshan/deblur_image/NAFNet-main/basicsr/models/base_model.py", line 57, in validation return self.nondist_validation(dataloader, current_iter, tb_logger, File "/data/pengshan/deblur_image/NAFNet-main/basicsr/models/image_restoration_model.py", line 385, in nondist_validation self.dist_validation(*args, **kwargs) File "/data/pengshan/deblur_image/NAFNet-main/basicsr/models/image_restoration_model.py", line 365, in dist_validation torch.distributed.reduce(metrics, dst=0) File "/data/pengshan/miniconda3/envs/pytorch-blur/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1469, in reduce default_pg = _get_default_group() File "/data/pengshan/miniconda3/envs/pytorch-blur/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 429, in _get_default_group raise RuntimeError( RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
> 
> 使用单个GPU训练，使用的是我自己的数据集，出现上述错误，麻烦帮忙看下是哪里的问题。 这个能使用单卡训练吗？

我也遇到了，修改参数后，但没用

**Comment by wang2001-hust** [comment]
在windows系统下单卡训练自己的数据集时（已经准备好train和val的文件及对应的lmdb文件），根据前序指导，执行torchrun --nproc_per_node=1 --master_port=4321 mytrain.py -opt options/train/mydata/NAFNet-width64.yml --launcher pytorch
但是会爆出无法连接至4321端口的问题：The client socket has failed to connect to [DESKTOP-N2B28CU]:4321 (system error: 10049 - 在其上下文中，该请求的地址无效。).这一问题不知如何解决。
以及nccl在windows下不支持的问题：C:\Users\dell\anaconda3\envs\VideoDeturb\Lib\site-packages\torch\distributed\distributed_c10d.py:613: UserWarning: Attempted to get default timeout for nccl backend, but NCCL support is not compiled
  warnings.warn("Attempted to get default timeout for nccl backend, but NCCL support is not compiled")
对此我在我的yml配置文件里修改了dist_params: backend: gloo，以及在训练文件中添加了    import os
os.environ["PL_TORCH_DISTRIBUTED_BACKEND"] = "gloo"，但是仍然爆出同样的错误。
我该如何修改我的yml文件以及如何修改train文件呢



> 您好， 看上去是在validation的时候用到了分布式训练的一些参数导致的问题，
> 
> 单卡训练可以考虑使用
> 
> ```
> python -m torch.distributed.launch --nproc_per_node=1 --master_port=4321 basicsr/train.py -opt _PATH_TO_YOUR_CONFIG_ --launcher pytorch
> ```
> 
> 避免特殊处理的麻烦
> 
> 谢谢您对NAFNe的关注

**Comment by miyan23** [comment]
单GPU训练不成功的原因是项目没有准备非分布式验证却调用了非分布式验证，在image_restoration_model.py的非分布式验证nondist_validation函数中又再次调用了分布式验证self.dist_validation函数。
解决方法是重构nondist_validation函数，改为单GPU版本：

    def nondist_validation(self, dataloader, current_iter, tb_logger, save_img, rgb2bgr, use_image):
        dataset_name = dataloader.dataset.opt['name']
        with_metrics = self.opt['val'].get('metrics') is not None
        if with_metrics:
            self.metric_results = {
                metric: 0
                for metric in self.opt['val']['metrics'].keys()
            }

        pbar = tqdm(total=len(dataloader), unit='image')
        cnt = 0

        for idx, val_data in enumerate(dataloader):
            img_name = osp.splitext(osp.basename(val_data['lq_path'][0]))[0]

            self.feed_data(val_data, is_val=True)
            if self.opt['val'].get('grids', False):
                self.grids()

            self.test()

            if self.opt['val'].get('grids', False):
                self.grids_inverse()

            visuals = self.get_current_visuals()
            sr_img = tensor2img([visuals['result']], rgb2bgr=rgb2bgr)
            if 'gt' in visuals:
                gt_img = tensor2img([visuals['gt']], rgb2bgr=rgb2bgr)
                del self.gt

            del self.lq
            del self.output
            torch.cuda.empty_cache()

            if save_img:
                if sr_img.shape[2] == 6:
                    L_img = sr_img[:, :, :3]
                    R_img = sr_img[:, :, 3:]

                    visual_dir = osp.join(self.opt['path']['visualization'], dataset_name)
                    imwrite(L_img, osp.join(visual_dir, f'{img_name}_L.png'))
                    imwrite(R_img, osp.join(visual_dir, f'{img_name}_R.png'))
                else:
                    if self.opt['is_train']:
                        save_img_path = osp.join(self.opt['path']['visualization'],
                                                 img_name,
                                                 f'{img_name}_{current_iter}.png')
                        save_gt_img_path = osp.join(self.opt['path']['visualization'],
                                                 img_name,
                                                 f'{img_name}_{current_iter}_gt.png')
                    else:
                        save_img_path = osp.join(
                            self.opt['path']['visualization'], dataset_name,
                            f'{img_name}.png')
                        save_gt_img_path = osp.join(
                            self.opt['path']['visualization'], dataset_name,
                            f'{img_name}_gt.png')
                    imwrite(sr_img, save_img_path)
                    imwrite(gt_img, save_gt_img_path)

            if with_metrics:
                opt_metric = deepcopy(self.opt['val']['metrics'])
                if use_image:
                    for name, opt_ in opt_metric.items():
                        metric_type = opt_.pop('type')
                        self.metric_results[name] += getattr(
                            metric_module, metric_type)(sr_img, gt_img, **opt_)
                else:
                    for name, opt_ in opt_metric.items():
                        metric_type = opt_.pop('type')
                        self.metric_results[name] += getattr(
                            metric_module, metric_type)(visuals['result'], visuals['gt'], **opt_)
                        
            cnt += 1
            pbar.update(1)
            pbar.set_description(f'Test {img_name}')

        pbar.close()

        if with_metrics:
            for metric in self.metric_results.keys():
                self.metric_results[metric] /= cnt

            self._log_validation_metric_values(current_iter, dataset_name,
                                               tb_logger, self.metric_results)

        return 0.

修改之后直接使用命令python basicsr/test.py -opt ./options/test/SIDD/NAFNet-width64.yml测试。
我这样解决了test.py的单GPU运行问题，train训练还没有尝试，不过应该是同一个问题，提供参考。
